
/**************************************************************
 *	
 *	battle, 8 bit, 11025Hz,
 *	1 channel, 814205 bytes/channel
 *	Total Size: 1 * 814205 + 4 (header) = 814249 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\John\Documents\School\CS 2261\M2_JohnHo\battle.wav
 *	Time-stamp: Mon Dec 04 19:25:17 2017
 *	
 **************************************************************/

#ifndef __BATTLEH__
#define __BATTLEH__

#define BATTLEFREQ 11025
#define BATTLELEN 814205

extern const unsigned char battle[814205];

#endif /* __BATTLEH__ */
