
/**************************************************************
 *	
 *	fireball, 8 bit, 11025Hz,
 *	1 channel, 8976 bytes/channel
 *	Total Size: 1 * 8976 + 4 (header) = 9020 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\John\Documents\School\CS 2261\M2_JohnHo\fireball.wav
 *	Time-stamp: Mon Dec 04 19:58:55 2017
 *	
 **************************************************************/

#ifndef __FIREBALLH__
#define __FIREBALLH__

#define FIREBALLFREQ 11025
#define FIREBALLLEN 8976

extern const unsigned char fireball[8976];

#endif /* __FIREBALLH__ */
