
/**************************************************************
 *	
 *	hurt, 8 bit, 11025Hz,
 *	1 channel, 3912 bytes/channel
 *	Total Size: 1 * 3912 + 4 (header) = 3956 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\John\Documents\School\CS 2261\M2_JohnHo\hurt.wav
 *	Time-stamp: Mon Dec 04 22:02:32 2017
 *	
 **************************************************************/

#ifndef __HURTH__
#define __HURTH__

#define HURTFREQ 11025
#define HURTLEN 3912

extern const unsigned char hurt[3912];

#endif /* __HURTH__ */
