
/**************************************************************
 *	
 *	lost, 8 bit, 11025Hz,
 *	1 channel, 10944 bytes/channel
 *	Total Size: 1 * 10944 + 4 (header) = 10988 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\John\Documents\School\CS 2261\M2_JohnHo\lost.wav
 *	Time-stamp: Tue Dec 05 03:17:20 2017
 *	
 **************************************************************/

#ifndef __LOSTH__
#define __LOSTH__

#define LOSTFREQ 11025
#define LOSTLEN 10944

extern const unsigned char lost[10944];

#endif /* __LOSTH__ */
