
/**************************************************************
 *	
 *	menuMusic, 8 bit, 11025Hz,
 *	1 channel, 697011 bytes/channel
 *	Total Size: 1 * 697011 + 4 (header) = 697055 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\John\Documents\School\CS 2261\M2_JohnHo\menuMusic.wav
 *	Time-stamp: Tue Dec 05 23:00:40 2017
 *	
 **************************************************************/

#ifndef __MENUMUSICH__
#define __MENUMUSICH__

#define MENUMUSICFREQ 11025
#define MENUMUSICLEN 697011

extern const unsigned char menuMusic[697011];

#endif /* __MENUMUSICH__ */
